- examples/mqtt_yun/mqtt_yun.ino
I may be mistaken, but I think all of the printing is to `Console`, and maybe in preparing this example, one call to `Serial` was missed.
> Yun example: change one Serial -> Console

- Adafruit_MQTT.cpp
- Adafruit_MQTT.h
- Adafruit_MQTT_CC3000.h
- Adafruit_MQTT_Client.h
- Adafruit_MQTT_FONA.h
- examples/adafruitio_anon_time_esp8266/adafruitio_anon_time_esp8266.ino
- library.properties
* adds the ability to connect to MQTT brokers without a username or password
* you can now set username & pass outside of the constructor via `connect()`
* adds support for adafruit_io_arduino callbacks
> Add Support for Adafruit IO Arduino

- Adafruit_MQTT_Client.cpp
Using the https://github.com/stm32duino/Arduino_Core_STM32 with Adafruit_MQTT_Library, there is a build issue.
```
.../libraries/Adafruit_MQTT_Library/Adafruit_MQTT_Client.cpp: In member function 'virtual bool Adafruit_MQTT_Client::sendPacket(uint8_t*, uint16_t)':
.../libraries/Adafruit_MQTT_Library/Adafruit_MQTT_Client.cpp:84:38: error: no matching function for call to 'min(uint16_t&, int)'
uint16_t sendlen = min(len, 250);
^
...
.../packages/STM32/tools/arm-none-eabi-gcc/6-2017-q2-update/arm-none-eabi/include/c++/6.3.1/bits/stl_algo.h:3453:5: note: candidate: template<class _Tp, class _Compare> _Tp std::min(std::initializer_list<_Tp>, _Compare)
min(initializer_list<_Tp> __l, _Compare __comp)
```
This patch allows to use min function of the standard C++ library without break …
> Fix min() usage when using STL C++

- Adafruit_MQTT_Client.cpp
see https://github.com/adafruit/Adafruit_MQTT_Library/issues/106  for discussion of link failures after upgrading esp8266 community library  BSP to version 2.4.0  --  removing the use of min() allows for successful compilation,link and execution.
Replace call to min() with ternary statement to accomplish same action.
Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:
- **Describe the scope of your change--i.e. what the change does and what parts
of the code were modified.**  This will help us understand any risks of integrating
the code.
- **Describe any known limitations with your change.**  For example if the change
doesn't apply to a supported …
> Update Adafruit_MQTT_Client.cpp to remove use of min()

- examples/adafruitio_secure_esp8266/adafruitio_secure_esp8266.ino
This PR updates the secure ESP8266 example sketch to use the new Adafruit IO TLS fingerprint.
> update IO TLS fingerprint

- Adafruit_MQTT.h
Perform a check for 32u4/328p-based devices (MAXSUBSCRIPTIONS = 5) and increase the subscription cap to 15 for non-32u4/328p: devices.
https://github.com/adafruit/Adafruit_MQTT_Library/blob/master/Adafruit_MQTT.h#L109
Tracking issue https://github.com/adafruit/Adafruit_MQTT_Library/issues/129
> increase mqtt sub. limit for non 32u4/328p devices

- examples/adafruitio_secure_esp8266/adafruitio_secure_esp8266.ino
- library.properties
Addressing https://github.com/adafruit/Adafruit_MQTT_Library/issues/142:
* Fixed SHA1 fingerprint for Adafruit IO
* Modified `#define`s for WLAN_SSID, WLAN_PASS, `AIO_SERVERPORT`, `AIO_USERNAME`, `AIO_KEY`.
* Bump `library.version`
```
IP address: 
SNIP!
Connecting to io.adafruit.com
Connection secure.
Sending val 0 to test feed...OK!
....
Sending val 61 to test feed...OK!
Sending val 62 to test feed...OK!
Sending val 63 to test feed...OK!
```
> fix sha1 fingerprint for io.adafruit.com

- keywords.txt
small pr - removing left-over reference to ADAFRUIT_MQTT_CC3000 (unsupported by this library) in `keywords.txt`
> remove CC3000 from keywords.txt

- Adafruit_MQTT.cpp
Adding IFDEF to include `*dtostrf` function when compiling for M4 hardware. I could also replace ARDUINO_SAMD_ZERO with ARDUINO_ARCH_SAMD?
Tested with PyPortal and nina-fw's WiFiClient connecting to Adafruit.IO.
> Update for M4 hardware

- examples/adafruitio_secure_esp8266/adafruitio_secure_esp8266.ino
- library.properties
ESP8266 BSP 2.5.1's `WiFiClientSecure` switched to `BearSSL` as the default (https://github.com/esp8266/Arduino/blob/2.5.1/libraries/ESP8266WiFi/src/WiFiClientSecure.h#L27) and is now compatible with this library again.
Adafruit IO MQTT (Insecure) runs OK with BSP2.5.1, but the secure client breaks and will not connect to Adafruit IO.
Scope of changes:
* Removed `verifyFingerprint()` function from `adafruitio_secure_esp8266.ino`
* Added new `client.setFingerprint()` function to the setup, used by BearSSL's validation.
* Removed Arduino v1.6.6 function declarations from `adafruitio_secure_esp8266.ino`
* Bump library version
Successfully tested on a Feather Huzzah ESP8266 w/BSP2.5.1
> Fixing example for ESP8266 (BSP 2.5.1) 

- Adafruit_MQTT.cpp
Added "defined(ARDUINO_SAMD_MKR1010)" into line 24 of Adafruit_MQTT.ccp to add support for the Arduino MKR1010 WiFi.
> Added support for the MKR1010

- Adafruit_MQTT_Client.h
- Adafruit_MQTT_FONA.h
Switched the following four methods from public to
protected in Adafruit_MQTT_Client and Adafruit_MQTT_FONA:
1. connectServer
2. disconnectServer
3. readPacket
4. sendPacket
When public (previously) they could be called by users
of this library, which is not the intent of this API.
Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:
- **Describe the scope of your change--i.e. what the change does and what parts
of the code were modified.**  This will help us understand any risks of integrating
the code.
- **Describe any known limitations with your change.**  For example if the change
doesn't apply to a supported platform of the library please mention …
> Corrected client public/private methods.

- Adafruit_MQTT.cpp
- Adafruit_MQTT_Client.cpp
- library.properties
Send multiple 250 byte packets for a large message (this was proposed in [PR113](https://github.com/adafruit/Adafruit_MQTT_Library/pull/113), but the change here should work for existing implementations that only support 250 byte packets by breaking the message into chunks).
Correctly identify topic start position for >127byte messages (may also be addressed in [PR166](https://github.com/adafruit/Adafruit_MQTT_Library/pull/166) -- happy to merge that fix in if preferred). 
Resolves [issue 102](https://github.com/adafruit/Adafruit_MQTT_Library/issues/102).
Tested on Wemos D1 mini (ESP8266) with messages up to 1023 bytes (set MAXBUFFERSIZE and SUBSCRIPTIONDATALEN to 1024).
> Support publishing and receiving large messages.

- Adafruit_MQTT.cpp
- Adafruit_MQTT.h
- library.properties
Allows the user to set the MQTT connection's keep alive interval time period in seconds via `setKeepAliveInterval()`. Previously, this time period was defined in the header. The function also checks if `connect()` was called prior.
Addresses https://github.com/adafruit/Adafruit_MQTT_Library/issues/186
Tested with multiple time intervals against Adafruit IO.
> Add setKeepAliveInterval() setter

- Adafruit_MQTT.cpp
- Adafruit_MQTT.h
When I'm working with the library, I detect that some event was lost. After enabled debug, I've detected 2 situations:
1. Ping call processPacketsUntil which detect if call new message (appears in debug console), but can't be read in callback or readSubscription.
My fix add a boolean attribute "new_message" (default false) in Adafruit_MQTT_Publish class. It is set to true inside processPacketsUntil. Later, in readSubscription, search if there are pending message. If so, return that message.
Callback don't need to be modified because it call readSubscription.
1. Sometimes my program fail to publish a message and loss subscription arrived (detected in debug console). The fix was more easy and clean: replase readFullPacket with processPacketsUntil. This permit that a message arrive when …
> Fix: Subscriptions can't be read if arrive when waiting for response of ping or publish

- Adafruit_MQTT.cpp
Further testing of my recent patch uncovered a new issue: the packet length calculation is off by +1 when the payload size is greater than 128 bytes. This length is stored in the MQTT packet header, so the broker is expecting a packet that is one byte longer than what gets sent (and times out or otherwise fails). The length stored in the MQTT packet header is the "remaining length" (see e.g. http://www.steves-internet-guide.com/mqtt-protocol-messages-overview/) and shouldn't include itself in the calculation.
> Fixed length calculation when payload exceeds 128bytes

- Adafruit_MQTT.cpp
- Adafruit_MQTT.h
- library.properties
Callback functions within subscription packets are currently not processed if `processPacketsUntil()` receives a subscription packet. While `processPacketsUntil()` does call `handleSubscriptionPacket()`, `handleSubscriptionPacket()` fills the `Adafruit_Subscription` object but does not call the callbacks as mentioned in its docstring ("// Handle any data coming in for subscriptions and fires them off to the appropriate callback") nor does it mark the subscription message as "read" (implemented in https://github.com/adafruit/Adafruit_MQTT_Library/pull/195). 
This causes any subscription packet picked up during `processPacketsUntil()`'s period (called by a `ping()` or `publish()`) to never execute its callback method. 
This pull request:
* Adds a new method, `processSubscriptionPacket` …
> Fix subscription packet callbacks not executing within processPacketsUntil()

- Adafruit_MQTT.cpp
- Adafruit_MQTT.h
- library.properties
This PR fixes return type of `connectErrorString` due to a change in https://github.com/espressif/arduino-esp32/pull/7941 by adding a preprocessor for ESP32-arch and returning a const char * rather than a `__FlashStringHelper` to `Serial.println()`.
Related: https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/2483
> Fix connectErrorString return type for ESP-32 BSP 2.0.8

- Adafruit_MQTT.cpp
- Adafruit_MQTT.h
- library.properties
Reverts adafruit/Adafruit_MQTT_Library#222
**Why?** "Arduino Release v2.0.9 based on ESP-IDF v4.4.4" PR https://github.com/espressif/arduino-esp32/pull/8147 is to "revert to the previous definition of FPSTR and F macros."
> Revert "Fix connectErrorString return type for ESP-32 BSP 2.0.8"

- examples/adafruitio_secure_esp8266/adafruitio_secure_esp8266.ino
The SHA1 fingerprint of io.adafruit.com is expired in the example used in this repo
The new correct fingerprint is "23 97 B0 6A 5A DA 2C F7 F3 3D 0E AB 9B E8 F7 3A 97 A4 07 C1"
This PR solves #230
> Update io.adafruit.com certificate fingerprint
